[project]
name = "a11y_wcag_testing"
version = "0.1.0"
description = "WCAG 2.2 Testing Tool with AI-powered analysis"
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
dependencies = [
    "crewai[tools]>=0.76.9",
    "crewai-tools>=0.13.4",
    "beautifulsoup4>=4.12.2",
    "requests>=2.31.0",
    "pydantic>=2.5.2",
    "selenium>=4.15.2",
    "playwright>=1.40.0",
    "aiofiles>=24.1.0",
    "crewai",
    "pyyaml",
    "jinja2",
    "langtrace-python-sdk",
    "selenium-webdriver",
    "axe-selenium-python",
]

[project.scripts]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
